version: '3.1'
services:
  ps_postgresql:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: paymentservice
      POSTGRES_PASSWORD: paymentservice

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080